CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    username VARCHAR(100) UNIQUE,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255)
);

ALTER TABLE users
ADD COLUMN tutor BOOLEAN NOT NULL,
ADD COLUMN student BOOLEAN NOT NULL;